"""Client state constants and type alias."""

from typing import Literal, TypeAlias

from _netcode import _client_state  # type: ignore[import-untyped]

CONNECT_TOKEN_EXPIRED: Literal["CONNECT_TOKEN_EXPIRED"] = (
    _client_state.CONNECT_TOKEN_EXPIRED
)
CONNECTION_TIMED_OUT: Literal["CONNECTION_TIMED_OUT"] = (
    _client_state.CONNECTION_TIMED_OUT
)
CONNECTION_REQUEST_TIMED_OUT: Literal["CONNECTION_REQUEST_TIMED_OUT"] = (
    _client_state.CONNECTION_REQUEST_TIMED_OUT
)
CHALLENGE_RESPONSE_TIMED_OUT: Literal["CHALLENGE_RESPONSE_TIMED_OUT"] = (
    _client_state.CHALLENGE_RESPONSE_TIMED_OUT
)
CONNECTION_DENIED: Literal["CONNECTION_DENIED"] = _client_state.CONNECTION_DENIED
DISCONNECTED: Literal["DISCONNECTED"] = _client_state.DISCONNECTED
SENDING_CONNECTION_REQUEST: Literal["SENDING_CONNECTION_REQUEST"] = (
    _client_state.SENDING_CONNECTION_REQUEST
)
SENDING_CHALLENGE_RESPONSE: Literal["SENDING_CHALLENGE_RESPONSE"] = (
    _client_state.SENDING_CHALLENGE_RESPONSE
)
CONNECTED: Literal["CONNECTED"] = _client_state.CONNECTED

ClientState: TypeAlias = Literal[
    "CONNECT_TOKEN_EXPIRED",
    "CONNECTION_TIMED_OUT",
    "CONNECTION_REQUEST_TIMED_OUT",
    "CHALLENGE_RESPONSE_TIMED_OUT",
    "CONNECTION_DENIED",
    "DISCONNECTED",
    "SENDING_CONNECTION_REQUEST",
    "SENDING_CHALLENGE_RESPONSE",
    "CONNECTED",
]
